# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "sdhci_pci"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "none";
    fsType = "tmpfs";
    options = ["defaults" "size=2G" "mode=755"];
  };

  fileSystems."/snapshot" = {
    device = "/dev/disk/by-uuid/b340044a-6dd1-46a9-83be-5a698008317c";
    fsType = "btrfs";
    options = ["subvol=@snapshot"];
  };

  fileSystems."/persistent" = {
    device = "/dev/disk/by-uuid/b340044a-6dd1-46a9-83be-5a698008317c";
    fsType = "btrfs";
    neededForBoot = true;
    options = ["subvol=@persistent" "compress=zstd"];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/b340044a-6dd1-46a9-83be-5a698008317c";
    fsType = "btrfs";
    options = ["subvol=nix" "compress-force=zstd"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/9471-BE0B";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/fb64720f-b645-46a9-933f-b51188460b38";}
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
